### ISSUE TITLE
compilation-mode error matching

### ISSUE THREAD

**Issue by gregghz** [tues/emacs-bloop#1]
I've added this to get links to files in the current project in a compilation-mode buffer:

```
(add-to-list 'compilation-error-regexp-alist-alist '(bloop "^\\[E\\] \\[E[0-9]+\\] \\(.*\\):\\([0-9]+\\):\\([0-9]+\\)$" 1 2 3))
(add-to-list 'compilation-error-regexp-alist 'bloop)
```

It might make sense to add this where you have the global keybinding set. I haven't tested this a ton, but it seems to work. If this looks alright to you, I'll go ahead and create a PR.

**Comment by tues** [comment]
Well, the keybindings shouldn't be there, obviously - I was simply lazy and committed them for my own convenience. I'll try to clean this repo up a bit now that I'm not the only one using this code.

I'll gladly accept any PRs you make, this is in pre-alpha stage so experimentation is fine IMO.

**Comment by tues** [comment]
Actually, for me the links work even without these custom regexps, the only issue being that the `[E] ` gets underlined as well, but links work fine anyway.

Oh, now I see: it's for the `bloop` reporter. Unfortunately it doesn't seem to work :disappointed: So I guess it's a good thing we're using `scalac` reporter by default now :slightly_smiling_face:

**Comment by gregghz** [comment]
Hmm, maybe there's something unique in my configuration. I won't worry about adding this to a PR for now. Good to have it documented here anyway.
